/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.6
  Forc version: 0.69.1
  Fuel-Core version: 0.45.1
*/

export { IpredictToken } from './IpredictToken';
export { IpredictTokenFactory } from './IpredictTokenFactory';
export { Leaderboard } from './Leaderboard';
export { LeaderboardFactory } from './LeaderboardFactory';
export { ReferralRegistry } from './ReferralRegistry';
export { ReferralRegistryFactory } from './ReferralRegistryFactory';
export { PredictionMarket } from './PredictionMarket';
export { PredictionMarketFactory } from './PredictionMarketFactory';
