/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.6
  Forc version: 0.69.1
  Fuel-Core version: 0.45.1
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
} from 'fuels';

import type { Enum } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum TokenErrorInput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', UnauthorizedMinter = 'UnauthorizedMinter', InsufficientBalance = 'InsufficientBalance', InvalidAmount = 'InvalidAmount', NotAdmin = 'NotAdmin' };
export enum TokenErrorOutput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', UnauthorizedMinter = 'UnauthorizedMinter', InsufficientBalance = 'InsufficientBalance', InvalidAmount = 'InvalidAmount', NotAdmin = 'NotAdmin' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type BurnEventInput = { from: IdentityInput, amount: BigNumberish };
export type BurnEventOutput = { from: IdentityOutput, amount: BN };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type MintEventInput = { to: IdentityInput, amount: BigNumberish };
export type MintEventOutput = { to: IdentityOutput, amount: BN };
export type MinterChangedEventInput = { minter: ContractIdInput, authorized: boolean };
export type MinterChangedEventOutput = { minter: ContractIdOutput, authorized: boolean };
export type TransferEventInput = { from: IdentityInput, to: IdentityInput, amount: BigNumberish };
export type TransferEventOutput = { from: IdentityOutput, to: IdentityOutput, amount: BN };

const abi = {
  "programType": "contract",
  "specVersion": "1.1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum libraries::TokenError",
      "concreteTypeId": "3324be9ad7cf796f2683cfc9b6f6c5c1a8a50369e29fe07de5640f8bc9659b2c",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 2
    },
    {
      "type": "struct libraries::BurnEvent",
      "concreteTypeId": "4cec19118d531602be1cd85c83f80e7b1c0ed894d71c53d4d3fe69305af153ef",
      "metadataTypeId": 4
    },
    {
      "type": "struct libraries::MintEvent",
      "concreteTypeId": "5b0405c2be84eaf8aa1c5a345fc2602362637262a6a9502a8916a57aaf906f14",
      "metadataTypeId": 5
    },
    {
      "type": "struct libraries::MinterChangedEvent",
      "concreteTypeId": "6cb91353b10a06a394398b98054d7c704f28061fa3d16ce2db567237b71be237",
      "metadataTypeId": 6
    },
    {
      "type": "struct libraries::TransferEvent",
      "concreteTypeId": "d0bbeb1d9fda60951627b742c9d6de0020ab101d910d4b17cd7f63ab1f3c27dd",
      "metadataTypeId": 7
    },
    {
      "type": "struct std::bytes::Bytes",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb",
      "metadataTypeId": 9
    },
    {
      "type": "struct std::contract_id::ContractId",
      "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54",
      "metadataTypeId": 11
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 12
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    },
    {
      "type": "u8",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "enum libraries::TokenError",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "AlreadyInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "UnauthorizedMinter",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InsufficientBalance",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotAdmin",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Address",
          "typeId": 8
        },
        {
          "name": "ContractId",
          "typeId": 11
        }
      ]
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 3
    },
    {
      "type": "struct libraries::BurnEvent",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "from",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct libraries::MintEvent",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "to",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct libraries::MinterChangedEvent",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "minter",
          "typeId": 11
        },
        {
          "name": "authorized",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct libraries::TransferEvent",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "from",
          "typeId": 2
        },
        {
          "name": "to",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "buf",
          "typeId": 10
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "ptr",
          "typeId": 3
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "bytes",
          "typeId": 9
        }
      ]
    }
  ],
  "functions": [
    {
      "name": "balance",
      "inputs": [
        {
          "name": "account",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the token balance for `account`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "burn",
      "inputs": [
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Burn `amount` tokens from the caller's balance."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "decimals",
      "inputs": [],
      "output": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the number of decimals."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "initialize",
      "inputs": [
        {
          "name": "name",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "symbol",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "decimals",
          "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Initialize the token with metadata. Can only be called once."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " The caller becomes the admin."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "is_minter",
      "inputs": [
        {
          "name": "minter",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Check whether a given ContractId is an authorized minter."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "mint",
      "inputs": [
        {
          "name": "to",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Mint `amount` tokens to `to`. Caller must be an authorized minter"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " (identified by its ContractId via msg_sender())."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "name",
      "inputs": [],
      "output": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the token name."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "remove_minter",
      "inputs": [
        {
          "name": "minter",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Revoke a contract's minting permission. Admin only."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "set_minter",
      "inputs": [
        {
          "name": "minter",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Authorize a contract to call `mint`. Admin only."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Supports multiple minters (e.g. PredictionMarket + ReferralRegistry)."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "symbol",
      "inputs": [],
      "output": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the token symbol."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "total_supply",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the current total supply."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "transfer",
      "inputs": [
        {
          "name": "to",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "amount",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Transfer `amount` tokens from the caller to `to`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "3685279967350847855",
      "concreteTypeId": "3324be9ad7cf796f2683cfc9b6f6c5c1a8a50369e29fe07de5640f8bc9659b2c"
    },
    {
      "logId": "5542832804562408962",
      "concreteTypeId": "4cec19118d531602be1cd85c83f80e7b1c0ed894d71c53d4d3fe69305af153ef"
    },
    {
      "logId": "14832741149864513620",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
    },
    {
      "logId": "6558373291336461048",
      "concreteTypeId": "5b0405c2be84eaf8aa1c5a345fc2602362637262a6a9502a8916a57aaf906f14"
    },
    {
      "logId": "7834314276961126051",
      "concreteTypeId": "6cb91353b10a06a394398b98054d7c704f28061fa3d16ce2db567237b71be237"
    },
    {
      "logId": "15040873893002371221",
      "concreteTypeId": "d0bbeb1d9fda60951627b742c9d6de0020ab101d910d4b17cd7f63ab1f3c27dd"
    }
  ],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const storageSlots: StorageSlot[] = [
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "8d65fe8361ff7a61847841b97d87761151b846dacfc4b7d686ec0074897ce0e1",
    "value": "0900000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "bc0c6f4eb59d947e0b3fe49e660075049636972b5a84d89450de827298d98909",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cc810296276c1a8f95a9839c890da0814ec4cd69701f777654be6d879ad0e372",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class IpredictTokenInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    balance: FunctionFragment;
    burn: FunctionFragment;
    decimals: FunctionFragment;
    initialize: FunctionFragment;
    is_minter: FunctionFragment;
    mint: FunctionFragment;
    name: FunctionFragment;
    remove_minter: FunctionFragment;
    set_minter: FunctionFragment;
    symbol: FunctionFragment;
    total_supply: FunctionFragment;
    transfer: FunctionFragment;
  };
}

export class IpredictToken extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: IpredictTokenInterface;
  declare functions: {
    balance: InvokeFunction<[account: IdentityInput], BN>;
    burn: InvokeFunction<[amount: BigNumberish], void>;
    decimals: InvokeFunction<[], number>;
    initialize: InvokeFunction<[name: StdString, symbol: StdString, decimals: BigNumberish], void>;
    is_minter: InvokeFunction<[minter: ContractIdInput], boolean>;
    mint: InvokeFunction<[to: IdentityInput, amount: BigNumberish], void>;
    name: InvokeFunction<[], StdString>;
    remove_minter: InvokeFunction<[minter: ContractIdInput], void>;
    set_minter: InvokeFunction<[minter: ContractIdInput], void>;
    symbol: InvokeFunction<[], StdString>;
    total_supply: InvokeFunction<[], BN>;
    transfer: InvokeFunction<[to: IdentityInput, amount: BigNumberish], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
