/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.6
  Forc version: 0.69.1
  Fuel-Core version: 0.45.1
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum, Vec } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum LeaderboardErrorInput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', UnauthorizedCaller = 'UnauthorizedCaller', InvalidPoints = 'InvalidPoints' };
export enum LeaderboardErrorOutput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', UnauthorizedCaller = 'UnauthorizedCaller', InvalidPoints = 'InvalidPoints' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type PlayerEntryInput = { address: IdentityInput, points: BigNumberish };
export type PlayerEntryOutput = { address: IdentityOutput, points: BN };
export type PlayerStatsInput = { points: BigNumberish, total_bets: BigNumberish, won_bets: BigNumberish, lost_bets: BigNumberish };
export type PlayerStatsOutput = { points: BN, total_bets: number, won_bets: number, lost_bets: number };
export type PointsAwardedEventInput = { user: IdentityInput, points: BigNumberish, is_winner: boolean };
export type PointsAwardedEventOutput = { user: IdentityOutput, points: BN, is_winner: boolean };

const abi = {
  "programType": "contract",
  "specVersion": "1.1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum libraries::LeaderboardError",
      "concreteTypeId": "0776c1c50d19f323497d77fe8cea687abf632a84ccfc15aea20d7527be1e7e22",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 2
    },
    {
      "type": "struct libraries::PlayerEntry",
      "concreteTypeId": "6c7facffbadb9d1c9a6262eda766ecf5a3af0eae16584fdc09b17e925c50d7a0",
      "metadataTypeId": 5
    },
    {
      "type": "struct libraries::PlayerStats",
      "concreteTypeId": "6538b0ca2e6c6b8075c0b120b621be03e14bfae00349d88b2bea7abb03b86ca9",
      "metadataTypeId": 6
    },
    {
      "type": "struct libraries::PointsAwardedEvent",
      "concreteTypeId": "634bae56bf03bddb7e5e943f9a4f4a0a2470e09bee2e74ecb2f80304e5ca3328",
      "metadataTypeId": 7
    },
    {
      "type": "struct std::contract_id::ContractId",
      "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54",
      "metadataTypeId": 9
    },
    {
      "type": "struct std::vec::Vec<struct libraries::PlayerEntry>",
      "concreteTypeId": "14cde3d538bedf01c46623581d2bf60d45a219f4e4ab69945a7739805243865d",
      "metadataTypeId": 11,
      "typeArguments": [
        "6c7facffbadb9d1c9a6262eda766ecf5a3af0eae16584fdc09b17e925c50d7a0"
      ]
    },
    {
      "type": "u32",
      "concreteTypeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "enum libraries::LeaderboardError",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "AlreadyInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "UnauthorizedCaller",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidPoints",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Address",
          "typeId": 8
        },
        {
          "name": "ContractId",
          "typeId": 9
        }
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 3
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 4
    },
    {
      "type": "struct libraries::PlayerEntry",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "address",
          "typeId": 2
        },
        {
          "name": "points",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct libraries::PlayerStats",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "points",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "total_bets",
          "typeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
        },
        {
          "name": "won_bets",
          "typeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
        },
        {
          "name": "lost_bets",
          "typeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
        }
      ]
    },
    {
      "type": "struct libraries::PointsAwardedEvent",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "user",
          "typeId": 2
        },
        {
          "name": "points",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "is_winner",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::vec::RawVec",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "ptr",
          "typeId": 4
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        3
      ]
    },
    {
      "type": "struct std::vec::Vec",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "buf",
          "typeId": 10,
          "typeArguments": [
            {
              "name": "",
              "typeId": 3
            }
          ]
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        3
      ]
    }
  ],
  "functions": [
    {
      "name": "add_bonus_pts",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "points",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Award bonus `points` without touching win/loss counters."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Called by the ReferralRegistry for welcome-bonus and referral rewards."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "add_pts",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "points",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "is_winner",
          "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Award `points` to `user` and update win/loss counters."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Called by the PredictionMarket contract at claim time."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "get_points",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return cumulative leaderboard points for `user`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_rank",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the 1-based rank of `user` in the sorted leaderboard."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns 0 if the user is not in the top-N list."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_stats",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "6538b0ca2e6c6b8075c0b120b621be03e14bfae00349d88b2bea7abb03b86ca9",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return full aggregate stats for `user`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_top_players",
      "inputs": [
        {
          "name": "limit",
          "concreteTypeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
        }
      ],
      "output": "14cde3d538bedf01c46623581d2bf60d45a219f4e4ab69945a7739805243865d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the top `limit` players sorted by points descending."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " If `limit` exceeds the stored count, returns all stored entries."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "initialize",
      "inputs": [
        {
          "name": "market_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "referral_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " One-time initialization. Caller becomes admin."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "record_bet",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Increment the user's total-bets counter."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Called by the PredictionMarket contract on every `place_bet`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "537830257589875491",
      "concreteTypeId": "0776c1c50d19f323497d77fe8cea687abf632a84ccfc15aea20d7527be1e7e22"
    },
    {
      "logId": "7155004120603278811",
      "concreteTypeId": "634bae56bf03bddb7e5e943f9a4f4a0a2470e09bee2e74ecb2f80304e5ca3328"
    }
  ],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const storageSlots: StorageSlot[] = [
  {
    "key": "257d57a8a688a9c2ad4b9c62019979346e5e73afec87394f7ce3c76b352f4390",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7e8c8fbaf63f985563a407aa286d9f9f45be20a641e519dcf3a4026e9df7d81f",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cc810296276c1a8f95a9839c890da0814ec4cd69701f777654be6d879ad0e372",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class LeaderboardInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    add_bonus_pts: FunctionFragment;
    add_pts: FunctionFragment;
    get_points: FunctionFragment;
    get_rank: FunctionFragment;
    get_stats: FunctionFragment;
    get_top_players: FunctionFragment;
    initialize: FunctionFragment;
    record_bet: FunctionFragment;
  };
}

export class Leaderboard extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: LeaderboardInterface;
  declare functions: {
    add_bonus_pts: InvokeFunction<[user: IdentityInput, points: BigNumberish], void>;
    add_pts: InvokeFunction<[user: IdentityInput, points: BigNumberish, is_winner: boolean], void>;
    get_points: InvokeFunction<[user: IdentityInput], BN>;
    get_rank: InvokeFunction<[user: IdentityInput], number>;
    get_stats: InvokeFunction<[user: IdentityInput], PlayerStatsOutput>;
    get_top_players: InvokeFunction<[limit: BigNumberish], Vec<PlayerEntryOutput>>;
    initialize: InvokeFunction<[market_contract: ContractIdInput, referral_contract: ContractIdInput], void>;
    record_bet: InvokeFunction<[user: IdentityInput], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
