/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.6
  Forc version: 0.69.1
  Fuel-Core version: 0.45.1
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
} from 'fuels';

import type { Enum } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum MarketErrorInput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', NotAdmin = 'NotAdmin', MarketNotFound = 'MarketNotFound', MarketExpired = 'MarketExpired', MarketNotExpired = 'MarketNotExpired', MarketResolved = 'MarketResolved', MarketCancelled = 'MarketCancelled', MarketNotResolved = 'MarketNotResolved', BetTooSmall = 'BetTooSmall', OppositeSideBet = 'OppositeSideBet', AlreadyClaimed = 'AlreadyClaimed', NoBetFound = 'NoBetFound', InvalidAmount = 'InvalidAmount', NoFeesToWithdraw = 'NoFeesToWithdraw' };
export enum MarketErrorOutput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', NotAdmin = 'NotAdmin', MarketNotFound = 'MarketNotFound', MarketExpired = 'MarketExpired', MarketNotExpired = 'MarketNotExpired', MarketResolved = 'MarketResolved', MarketCancelled = 'MarketCancelled', MarketNotResolved = 'MarketNotResolved', BetTooSmall = 'BetTooSmall', OppositeSideBet = 'OppositeSideBet', AlreadyClaimed = 'AlreadyClaimed', NoBetFound = 'NoBetFound', InvalidAmount = 'InvalidAmount', NoFeesToWithdraw = 'NoFeesToWithdraw' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type BetInput = { amount: BigNumberish, is_yes: boolean, claimed: boolean };
export type BetOutput = { amount: BN, is_yes: boolean, claimed: boolean };
export type BetPlacedEventInput = { market_id: BigNumberish, user: IdentityInput, is_yes: boolean, amount: BigNumberish, net_amount: BigNumberish, fee: BigNumberish, is_increase: boolean };
export type BetPlacedEventOutput = { market_id: BN, user: IdentityOutput, is_yes: boolean, amount: BN, net_amount: BN, fee: BN, is_increase: boolean };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type FeesWithdrawnEventInput = { admin: IdentityInput, amount: BigNumberish };
export type FeesWithdrawnEventOutput = { admin: IdentityOutput, amount: BN };
export type MarketInput = { id: BigNumberish, question: StdString, image_url: StdString, end_time: BigNumberish, total_yes: BigNumberish, total_no: BigNumberish, resolved: boolean, outcome: boolean, cancelled: boolean, creator: IdentityInput, bet_count: BigNumberish };
export type MarketOutput = { id: BN, question: StdString, image_url: StdString, end_time: BN, total_yes: BN, total_no: BN, resolved: boolean, outcome: boolean, cancelled: boolean, creator: IdentityOutput, bet_count: number };
export type MarketCancelledEventInput = { market_id: BigNumberish, refunded_count: BigNumberish };
export type MarketCancelledEventOutput = { market_id: BN, refunded_count: number };
export type MarketCreatedEventInput = { market_id: BigNumberish, question: StdString, end_time: BigNumberish, creator: IdentityInput };
export type MarketCreatedEventOutput = { market_id: BN, question: StdString, end_time: BN, creator: IdentityOutput };
export type MarketResolvedEventInput = { market_id: BigNumberish, outcome: boolean };
export type MarketResolvedEventOutput = { market_id: BN, outcome: boolean };
export type OddsInput = { yes_percent: BigNumberish, no_percent: BigNumberish };
export type OddsOutput = { yes_percent: number, no_percent: number };
export type RewardClaimedEventInput = { market_id: BigNumberish, user: IdentityInput, is_winner: boolean, payout: BigNumberish, points: BigNumberish, tokens: BigNumberish };
export type RewardClaimedEventOutput = { market_id: BN, user: IdentityOutput, is_winner: boolean, payout: BN, points: BN, tokens: BN };

const abi = {
  "programType": "contract",
  "specVersion": "1.1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum libraries::MarketError",
      "concreteTypeId": "fb2853b2d80f843bf8aadf8a5eb8bc1efafcb1bbfa610fe99f1098473de324e3",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 2
    },
    {
      "type": "struct libraries::Bet",
      "concreteTypeId": "0bb6ec9b44971a6defd5ea4071568b9760e4183422b50560c225aa908284c3fd",
      "metadataTypeId": 4
    },
    {
      "type": "struct libraries::BetPlacedEvent",
      "concreteTypeId": "c824365a7b5affba30b84d67606bcd4e5b163652fe79dbd0d927ef3d0c12f63a",
      "metadataTypeId": 5
    },
    {
      "type": "struct libraries::FeesWithdrawnEvent",
      "concreteTypeId": "566f541e55dff6abbe40f7ec0e82895751f82569484c99ec88c1bc3ccedfd8aa",
      "metadataTypeId": 6
    },
    {
      "type": "struct libraries::Market",
      "concreteTypeId": "f4dd4f934393c404cff87308c82bef32725a32047a466df1fef921f5600c16d1",
      "metadataTypeId": 7
    },
    {
      "type": "struct libraries::MarketCancelledEvent",
      "concreteTypeId": "25236d5f337d4badf1060a25a62af12f5da672126c09cfe923f628159eb23e51",
      "metadataTypeId": 8
    },
    {
      "type": "struct libraries::MarketCreatedEvent",
      "concreteTypeId": "22e38ea8923048445ace3493e6233b36ab85ce24de4d3f5b3597c4ca803a9750",
      "metadataTypeId": 9
    },
    {
      "type": "struct libraries::MarketResolvedEvent",
      "concreteTypeId": "db77b5b9d0863f8dbf19819437bb88f9e458b7afee6290d155b7f0670fd0e774",
      "metadataTypeId": 10
    },
    {
      "type": "struct libraries::Odds",
      "concreteTypeId": "1c1685116dda8e0d2ea0c1a615c5b9625e85ba94478a731e6197565d5720b1ff",
      "metadataTypeId": 11
    },
    {
      "type": "struct libraries::RewardClaimedEvent",
      "concreteTypeId": "5c643b83783dedd038269c39fc6a7c69b8191b045948877f3e8ddeef13df010c",
      "metadataTypeId": 12
    },
    {
      "type": "struct std::contract_id::ContractId",
      "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54",
      "metadataTypeId": 16
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 17
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "enum libraries::MarketError",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "AlreadyInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotAdmin",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MarketNotFound",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MarketExpired",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MarketNotExpired",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MarketResolved",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MarketCancelled",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "MarketNotResolved",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "BetTooSmall",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OppositeSideBet",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AlreadyClaimed",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NoBetFound",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NoFeesToWithdraw",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Address",
          "typeId": 13
        },
        {
          "name": "ContractId",
          "typeId": 16
        }
      ]
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 3
    },
    {
      "type": "struct libraries::Bet",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "is_yes",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "claimed",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct libraries::BetPlacedEvent",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "market_id",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "user",
          "typeId": 2
        },
        {
          "name": "is_yes",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "net_amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "fee",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "is_increase",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct libraries::FeesWithdrawnEvent",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "admin",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct libraries::Market",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "id",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "question",
          "typeId": 17
        },
        {
          "name": "image_url",
          "typeId": 17
        },
        {
          "name": "end_time",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "total_yes",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "total_no",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "resolved",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "outcome",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "cancelled",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "creator",
          "typeId": 2
        },
        {
          "name": "bet_count",
          "typeId": 18
        }
      ]
    },
    {
      "type": "struct libraries::MarketCancelledEvent",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "market_id",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "refunded_count",
          "typeId": 18
        }
      ]
    },
    {
      "type": "struct libraries::MarketCreatedEvent",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "market_id",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "question",
          "typeId": 17
        },
        {
          "name": "end_time",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "creator",
          "typeId": 2
        }
      ]
    },
    {
      "type": "struct libraries::MarketResolvedEvent",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "market_id",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "outcome",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct libraries::Odds",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "yes_percent",
          "typeId": 18
        },
        {
          "name": "no_percent",
          "typeId": 18
        }
      ]
    },
    {
      "type": "struct libraries::RewardClaimedEvent",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "market_id",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "user",
          "typeId": 2
        },
        {
          "name": "is_winner",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "payout",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "points",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "tokens",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 13,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 14,
      "components": [
        {
          "name": "buf",
          "typeId": 15
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 15,
      "components": [
        {
          "name": "ptr",
          "typeId": 3
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 16,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 17,
      "components": [
        {
          "name": "bytes",
          "typeId": 14
        }
      ]
    },
    {
      "type": "u32",
      "metadataTypeId": 18
    }
  ],
  "functions": [
    {
      "name": "cancel_market",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Cancel a market and refund all bettors their net bet amounts."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Admin only. Market must not be already resolved or cancelled."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "claim",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Claim rewards for a resolved market."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Winners receive proportional ETH payout from the total pool."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " All participants (winners + losers) receive leaderboard points and"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " IPREDICT tokens via inter-contract calls."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "create_market",
      "inputs": [
        {
          "name": "question",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "image_url",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "duration_secs",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Create a new prediction market. Admin only."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " `duration_secs` is added to the current block timestamp to set `end_time`."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns the new market ID (1-based)."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "get_accumulated_fees",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the current accumulated platform fees."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_bet",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "0bb6ec9b44971a6defd5ea4071568b9760e4183422b50560c225aa908284c3fd",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the Bet struct for a user on a given market."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_market",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "f4dd4f934393c404cff87308c82bef32725a32047a466df1fef921f5600c16d1",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the full Market struct for the given ID."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_market_count",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the total number of markets created."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_odds",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "1c1685116dda8e0d2ea0c1a615c5b9625e85ba94478a731e6197565d5720b1ff",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the current YES/NO probability split for a market."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "initialize",
      "inputs": [
        {
          "name": "token_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "referral_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "leaderboard_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " One-time initialization. Caller becomes admin."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "place_bet",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "is_yes",
          "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Place a bet on a market. Caller sends ETH with the call."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " A 2% fee is deducted: 1.5% platform + 0.5% referral."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " If the user has no referrer, the full 2% goes to platform fees."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Users may increase their position on the same side but cannot"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " switch sides."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "name": "resolve_market",
      "inputs": [
        {
          "name": "market_id",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "outcome",
          "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Resolve a market with the given outcome. Admin only."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Can only be called after the market's end_time has passed."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "withdraw_fees",
      "inputs": [],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Transfer all accumulated platform fees to the admin. Admin only."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "18097807130182517819",
      "concreteTypeId": "fb2853b2d80f843bf8aadf8a5eb8bc1efafcb1bbfa610fe99f1098473de324e3"
    },
    {
      "logId": "2676102859241376685",
      "concreteTypeId": "25236d5f337d4badf1060a25a62af12f5da672126c09cfe923f628159eb23e51"
    },
    {
      "logId": "6657511585004514768",
      "concreteTypeId": "5c643b83783dedd038269c39fc6a7c69b8191b045948877f3e8ddeef13df010c"
    },
    {
      "logId": "2514009871661156420",
      "concreteTypeId": "22e38ea8923048445ace3493e6233b36ab85ce24de4d3f5b3597c4ca803a9750"
    },
    {
      "logId": "14421711668991688634",
      "concreteTypeId": "c824365a7b5affba30b84d67606bcd4e5b163652fe79dbd0d927ef3d0c12f63a"
    },
    {
      "logId": "15814308426206822285",
      "concreteTypeId": "db77b5b9d0863f8dbf19819437bb88f9e458b7afee6290d155b7f0670fd0e774"
    },
    {
      "logId": "6228289298943178411",
      "concreteTypeId": "566f541e55dff6abbe40f7ec0e82895751f82569484c99ec88c1bc3ccedfd8aa"
    }
  ],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const storageSlots: StorageSlot[] = [
  {
    "key": "257d57a8a688a9c2ad4b9c62019979346e5e73afec87394f7ce3c76b352f4390",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "395ebb19870ff9a01b516f9573cbc58aea698f2f2514c805c7d22b3e0fec038a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "697c9133e1af64a4b1a76e9191ed4d6d775d14d7aac396db24582cf638686b26",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "acce8d0396d4465b15ea0d75ff3a8346962857ce7b83f3e002c6e2bfe6aaeaa7",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "b08f3acdd95460cefbdab6b51c2f604727ac3b706de31f8db3bfc2183b1164e7",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cc810296276c1a8f95a9839c890da0814ec4cd69701f777654be6d879ad0e372",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class PredictionMarketInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    cancel_market: FunctionFragment;
    claim: FunctionFragment;
    create_market: FunctionFragment;
    get_accumulated_fees: FunctionFragment;
    get_bet: FunctionFragment;
    get_market: FunctionFragment;
    get_market_count: FunctionFragment;
    get_odds: FunctionFragment;
    initialize: FunctionFragment;
    place_bet: FunctionFragment;
    resolve_market: FunctionFragment;
    withdraw_fees: FunctionFragment;
  };
}

export class PredictionMarket extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: PredictionMarketInterface;
  declare functions: {
    cancel_market: InvokeFunction<[market_id: BigNumberish], void>;
    claim: InvokeFunction<[market_id: BigNumberish], void>;
    create_market: InvokeFunction<[question: StdString, image_url: StdString, duration_secs: BigNumberish], BN>;
    get_accumulated_fees: InvokeFunction<[], BN>;
    get_bet: InvokeFunction<[market_id: BigNumberish, user: IdentityInput], BetOutput>;
    get_market: InvokeFunction<[market_id: BigNumberish], MarketOutput>;
    get_market_count: InvokeFunction<[], BN>;
    get_odds: InvokeFunction<[market_id: BigNumberish], OddsOutput>;
    initialize: InvokeFunction<[token_contract: ContractIdInput, referral_contract: ContractIdInput, leaderboard_contract: ContractIdInput], void>;
    place_bet: InvokeFunction<[market_id: BigNumberish, is_yes: boolean], void>;
    resolve_market: InvokeFunction<[market_id: BigNumberish, outcome: boolean], void>;
    withdraw_fees: InvokeFunction<[], BN>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
