/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.6
  Forc version: 0.69.1
  Fuel-Core version: 0.45.1
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
} from 'fuels';

import type { Option, Enum } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum ReferralErrorInput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', UnauthorizedCaller = 'UnauthorizedCaller', AlreadyRegistered = 'AlreadyRegistered', SelfReferral = 'SelfReferral' };
export enum ReferralErrorOutput { AlreadyInitialized = 'AlreadyInitialized', NotInitialized = 'NotInitialized', UnauthorizedCaller = 'UnauthorizedCaller', AlreadyRegistered = 'AlreadyRegistered', SelfReferral = 'SelfReferral' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type ReferralCreditedEventInput = { user: IdentityInput, referrer: IdentityInput, amount: BigNumberish };
export type ReferralCreditedEventOutput = { user: IdentityOutput, referrer: IdentityOutput, amount: BN };
export type ReferralRegisteredEventInput = { user: IdentityInput, display_name: StdString, has_referrer: boolean };
export type ReferralRegisteredEventOutput = { user: IdentityOutput, display_name: StdString, has_referrer: boolean };

const abi = {
  "programType": "contract",
  "specVersion": "1.1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum libraries::ReferralError",
      "concreteTypeId": "2009403675fc32af0bbf18300c5477ebdb4cc8a479e4eeb04489e87f0325d6c3",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 2
    },
    {
      "type": "enum std::option::Option<enum std::identity::Identity>",
      "concreteTypeId": "253aea1197e8005518365bd24c8bc31f73a434fac0f7350e57696edfdd4850c2",
      "metadataTypeId": 3,
      "typeArguments": [
        "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
      ]
    },
    {
      "type": "struct libraries::ReferralCreditedEvent",
      "concreteTypeId": "b6c06943115e181f1d530837e0ca10ce9bf8fa504fa31697125e6d50948e206b",
      "metadataTypeId": 6
    },
    {
      "type": "struct libraries::ReferralRegisteredEvent",
      "concreteTypeId": "0abea380bbd6ff5e665b7b018a45767b0f167eee1f69d6f76e168e2a4afacf32",
      "metadataTypeId": 7
    },
    {
      "type": "struct std::contract_id::ContractId",
      "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54",
      "metadataTypeId": 11
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 12
    },
    {
      "type": "u32",
      "concreteTypeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "b256",
      "metadataTypeId": 0
    },
    {
      "type": "enum libraries::ReferralError",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "AlreadyInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "UnauthorizedCaller",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AlreadyRegistered",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SelfReferral",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Address",
          "typeId": 8
        },
        {
          "name": "ContractId",
          "typeId": 11
        }
      ]
    },
    {
      "type": "enum std::option::Option",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "None",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Some",
          "typeId": 4
        }
      ],
      "typeParameters": [
        4
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 4
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 5
    },
    {
      "type": "struct libraries::ReferralCreditedEvent",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "user",
          "typeId": 2
        },
        {
          "name": "referrer",
          "typeId": 2
        },
        {
          "name": "amount",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct libraries::ReferralRegisteredEvent",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "user",
          "typeId": 2
        },
        {
          "name": "display_name",
          "typeId": 12
        },
        {
          "name": "has_referrer",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "buf",
          "typeId": 10
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "ptr",
          "typeId": 5
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "bits",
          "typeId": 0
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "bytes",
          "typeId": 9
        }
      ]
    }
  ],
  "functions": [
    {
      "name": "credit",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "referral_fee",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Called by PredictionMarket on each bet. If the user has a referrer,"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " the referral fee (forwarded as ETH with this call) is transferred to the"
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " referrer, and bonus points are awarded. Returns `true` if fee was routed."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Returns `false` if user has no referrer (caller should retain the fee)."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "name": "get_display_name",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the display name for `user`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_earnings",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return cumulative ETH referral earnings for `user`."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_referral_count",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return how many users `user` has referred."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "get_referrer",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "253aea1197e8005518365bd24c8bc31f73a434fac0f7350e57696edfdd4850c2",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Return the referrer of `user`, or `None` if none was set."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "has_referrer",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Check whether `user` has a referrer set."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "initialize",
      "inputs": [
        {
          "name": "market_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "token_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "leaderboard_contract",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " One-time initialization. Caller becomes admin."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "name": "is_registered",
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Check whether `user` has registered."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "name": "register_referral",
      "inputs": [
        {
          "name": "display_name",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        },
        {
          "name": "referrer",
          "concreteTypeId": "253aea1197e8005518365bd24c8bc31f73a434fac0f7350e57696edfdd4850c2"
        }
      ],
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " Register the caller with a display name and optional referrer."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Awards welcome bonus: WELCOME_BONUS_POINTS via Leaderboard + WELCOME_BONUS_TOKENS via Token."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " If a referrer is provided, that referrer's referral_count is incremented."
          ]
        },
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "2308446886655963823",
      "concreteTypeId": "2009403675fc32af0bbf18300c5477ebdb4cc8a479e4eeb04489e87f0325d6c3"
    },
    {
      "logId": "13168641047206434847",
      "concreteTypeId": "b6c06943115e181f1d530837e0ca10ce9bf8fa504fa31697125e6d50948e206b"
    },
    {
      "logId": "774235959256874846",
      "concreteTypeId": "0abea380bbd6ff5e665b7b018a45767b0f167eee1f69d6f76e168e2a4afacf32"
    }
  ],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const storageSlots: StorageSlot[] = [
  {
    "key": "395ebb19870ff9a01b516f9573cbc58aea698f2f2514c805c7d22b3e0fec038a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "697c9133e1af64a4b1a76e9191ed4d6d775d14d7aac396db24582cf638686b26",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "7e8c8fbaf63f985563a407aa286d9f9f45be20a641e519dcf3a4026e9df7d81f",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780a",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "810e3b3dbe873997e5edec031e9d28a3214551a292100b5f5cd84da8e26d780b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cc810296276c1a8f95a9839c890da0814ec4cd69701f777654be6d879ad0e372",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class ReferralRegistryInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    credit: FunctionFragment;
    get_display_name: FunctionFragment;
    get_earnings: FunctionFragment;
    get_referral_count: FunctionFragment;
    get_referrer: FunctionFragment;
    has_referrer: FunctionFragment;
    initialize: FunctionFragment;
    is_registered: FunctionFragment;
    register_referral: FunctionFragment;
  };
}

export class ReferralRegistry extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: ReferralRegistryInterface;
  declare functions: {
    credit: InvokeFunction<[user: IdentityInput, referral_fee: BigNumberish], boolean>;
    get_display_name: InvokeFunction<[user: IdentityInput], StdString>;
    get_earnings: InvokeFunction<[user: IdentityInput], BN>;
    get_referral_count: InvokeFunction<[user: IdentityInput], number>;
    get_referrer: InvokeFunction<[user: IdentityInput], Option<IdentityOutput>>;
    has_referrer: InvokeFunction<[user: IdentityInput], boolean>;
    initialize: InvokeFunction<[market_contract: ContractIdInput, token_contract: ContractIdInput, leaderboard_contract: ContractIdInput], void>;
    is_registered: InvokeFunction<[user: IdentityInput], boolean>;
    register_referral: InvokeFunction<[display_name: StdString, referrer?: Option<IdentityInput>], void>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
